# Generated by Django 5.0.6 on 2024-10-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='lineamientos/')),
                ('titulo_secundario', models.CharField(max_length=100)),
                ('titulo_principal', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
