# Generated by Django 5.0.6 on 2025-01-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_recomendacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='lineamiento',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lineamiento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineamiento',
            name='objetivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineamiento',
            name='puntos_clave',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineamiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineamiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='lineamientos/'),
        ),
        migrations.AlterField(
            model_name='lineamiento',
            name='titulo_secundario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lineamiento',
            name='documentos',
            field=models.ManyToManyField(blank=True, to='myapp.documento'),
        ),
    ]
