# Generated by Django 5.0.6 on 2025-01-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_documento_lineamiento_categoria_lineamiento_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineamiento',
            name='puntos_clave',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
