# Generated by Django 5.1.4 on 2025-04-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_lineamiento_puntos_clave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineamiento",
            name="puntos_clave",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
