# Generated by Django 5.1.4 on 2025-04-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_pregunta_evaluacion_respuesta"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacion",
            name="nombre_proyecto",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
