# Generated by Django 5.1.4 on 2025-05-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_evaluacion_nombre_proyecto"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacion",
            name="promedio_agencia",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="promedio_bienestar",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="promedio_diversidad",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="promedio_responsabilidad",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="promedio_robustez",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluacion",
            name="promedio_transparencia",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
