# Generated by Django 5.1.4 on 2025-05-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_evaluacion_promedio_agencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacion",
            name="informe_gpt",
            field=models.TextField(
                blank=True, help_text="Aquí se almacena el informe generado por GPT"
            ),
        ),
    ]
